import dedent from "dedent-js";
import * as project from "../package.json";

export const header = () => dedent`
  ---!!! DO NOT MANUALLY EDIT THIS FILE !!!
  ---Generated by ${project.name} ${project.version}
  ---${project.homepage}
  ---
  ---@meta
`;
