import dedent from "dedent-js";
import * as project from "../package.json";
import { toLuaComment } from "./utility";

export function header(sourcePaths: string[]) {
  let sources = "";
  if (sourcePaths.length === 1) {
    sources = `\nSource: ${sourcePaths[0]}\n`;
  } else if (sourcePaths.length > 1) {
    sources = `\nSources:\n${sourcePaths.map((s) => ` - ${s}`).join("\n")}\n`;
  }
  return toLuaComment(dedent`
    !!! DO NOT MANUALLY EDIT THIS FILE !!!
    Generated by ${project.name} ${project.version}
    ${project.homepage}
    ${sources}
    @meta
  `);
}
