import { parse, Tag, Comment } from "./parser";
import * as project from "../package.json";
import chalk from "chalk";
import { logError } from "./log";
import { remove } from "lodash";

export function extract(path: string, source: string): string {
  return `
---!!! DO NOT MANUALLY EDIT THIS FILE !!!
---Generated by ${project.name} ${project.version}
---${project.homepage}
---
---Date: ${new Date().toUTCString()}
---Source: ${path}
---
---@meta

${members(source)}`;
}

function toLuaComment(lines: string[]): string | null {
  if (lines.length === 0) {
    return null;
  }
  return lines.map((line) => `---${line}`).join("\n");
}

function formatTag({ type, detail }: Tag): string {
  let result = `@${type}`;
  if (detail.length > 0) {
    result += ` ${detail.join("\n")}`;
  }
  return result;
}

function members(source: string): string {
  const comments = parse(source);
  const members = comments.reduce((acc, c) => {
    const lua = extractDeclaration(c);
    const desc = toLuaComment(c.description);
    const tags =
      c.tags.length === 0
        ? null
        : c.tags
            .map(formatTag)
            .map((t) => toLuaComment(t.split("\n")))
            .join("\n");
    acc.push(
      [desc, desc && tags && "---", tags, lua]
        .filter((s) => s != null)
        .join("\n")
    );
    return acc;
  }, [] as string[]);
  return members.join("\n\n");
}

const ruleHandlers = {
  function(rule: Tag, comment: Comment) {
    const paramNames = comment.tags
      .filter((t) => t.type === "param" && t.detail.length > 0)
      .map((t) => t.detail[0].split(/\s/, 1));

    if (rule.detail.length === 0) {
      logError(`@function tag missing function name: ${rule}`);
      return null;
    }
    const firstLine = rule.detail[0].trim();
    const functionName = firstLine.split(/\s/, 1)[0];
    if (rule.detail.length > 1 || functionName.length < firstLine.length) {
      console.warn(
        chalk.yellow`@function tag has unused data:\n` +
          `'${rule.detail.join("\n")}'\n`
      );
    }
    return `function ${functionName}(${paramNames.join(", ")}) end`;
  },
  metatable(rule: Tag, _comment: Comment) {
    return `${rule.detail.join(" ")} = {}`;
  },
};

type RuleType = keyof typeof ruleHandlers;

/** Must be called _before_ tags are used, as it modifies the tags array */
function extractDeclaration(comment: Comment): string | null {
  // Remove custom rule tags from list of tags.
  const rules = remove(comment.tags, (t) =>
    ruleHandlers.hasOwnProperty(t.type)
  ) as (Tag & { type: RuleType })[];

  if (rules.length === 0) {
    return null;
  }

  const [rule, ...unused] = rules;
  if (unused.length > 0) {
    console.warn(
      `Incompatible tags found in comment:\n` +
        chalk.rgb(255, 255, 0)(`${unused.map(formatTag).join("\n")}`) +
        `using: ${chalk.rgb(0, 255, 0)(formatTag(rule))}` +
        `\n---\n`
    );
  }

  return ruleHandlers[rule.type](rule, comment);
}
